"""
Retrieve a list of modules in the standard library

https://docs.python.org/2/py-modindex.html
"""

import requests
from lxml import etree

if __name__ == '__main__':
    tree2 = etree.HTML(requests.get('https://docs.python.org/2/py-modindex.html').content)
    tree3 = etree.HTML(requests.get('https://docs.python.org/3/py-modindex.html').content)
    with open('stdlib_modules_autogenerated.py', 'w') as f:
        f.write('python2_modules = {!r}\n'.format(
            set(x.text for x in tree2.xpath('//tt[@class="xref"]'))
        ))
        f.write('python3_modules = {!r}\n'.format(
            set(x.text for x in tree3.xpath('//tt[@class="xref"]'))
        ))
